(function(){"use strict";
const $=s=>document.querySelector(s), ui={status:$("#status"),prompt:$("#prompt"),caption:$("#caption"),mic:$("#mic"),card:$("#wordCard"),rows:$("#transcriptRows"),transcript:$("#transcript"),lesson:$("#lessonLabel")};
const orb=new VoiceOrb($("#teacherOrb"),{theme:"green"}); let socket=null,stream=null,ctx=null,source=null,processor=null,sessionId="",ended=false,playbackNextTime=0,playbackContext=null,playbackQueue=Promise.resolve(),playbackNodes=new Set();
function setState(state,text){ui.status.textContent=text;orb.setState(state,{synthetic:true});ui.mic.classList.toggle("live",state==="recording");ui.mic.classList.toggle("speaking",state==="playing");ui.mic.classList.toggle("active",["recording","playing","processing"].includes(state));const label=$("#micLabel");if(label)label.innerHTML=state==="recording"?"聆听中<br><small>Listening</small>":state==="playing"?"老师说话<br><small>Teacher</small>":state==="processing"?"连接中<br><small>Connecting</small>":"开始<br><small>Start</small>";}
function addLine(role,text){if(!text)return;const li=document.createElement("li");li.className=role==="student"?"student":"teacher";const label=role==="student"?"我 / Me":"点点老师 / Teacher";li.innerHTML=`<b>${label}：</b>${String(text).replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))}`;ui.rows.prepend(li);ui.rows.parentElement.scrollTop=0;}
function send(data){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(data));}
function gatewayUrl(){return String(window.HANZI_COMPANION_CONFIG?.realtimeTeacherGatewayUrl||"").replace(/\/+$/,"");}
async function start(){if(socket)return;const profile=LearningApi.profile();if(!["student","teacher","admin"].includes(profile?.role))throw new Error("请先登录学生、教师或管理员账号");if(!gatewayUrl())throw new Error("实时语音网关尚未配置");setState("processing","老师正在连接");ui.lesson.textContent=profile?.role==="admin"?"管理员体验对话":(profile?.bookId?"个性化中文对话":"中文水平诊断对话");socket=new WebSocket(gatewayUrl());socket.addEventListener("open",()=>send({type:"auth",token:LearningApi.token()}));socket.addEventListener("message",onMessage);socket.addEventListener("close",()=>{if(!ended)fail("连接已断开，请重试");cleanup(false)});socket.addEventListener("error",()=>fail("无法连接实时语音网关"));}
async function beginAudio(){stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});ctx=new AudioContext();source=ctx.createMediaStreamSource(stream);processor=ctx.createScriptProcessor(1024,1,1);let pending=[];processor.onaudioprocess=e=>{if(socket?.readyState!==WebSocket.OPEN)return;const input=e.inputBuffer.getChannelData(0),ratio=ctx.sampleRate/16000,outLength=Math.floor(input.length/ratio);for(let i=0;i<outLength;i++)pending.push(Math.max(-1,Math.min(1,input[Math.floor(i*ratio)]))*32767);while(pending.length>=320){const packet=new Int16Array(pending.splice(0,320));socket.send(packet.buffer)}};source.connect(processor);const mute=ctx.createGain();mute.gain.value=0;processor.connect(mute);mute.connect(ctx.destination);await orb.attachStream(stream);setState("recording","正在听你说");}
function stopAudio(){try{processor?.disconnect();source?.disconnect()}catch{}stream?.getTracks().forEach(t=>t.stop());processor=source=stream=null;ctx?.close().catch(()=>{});ctx=null;orb.detachAudio();}
function renderWordCard(hanzi,pinyin,meaning){const h=String(hanzi||"").trim(),syllables=String(pinyin||"").trim().split(/\s+/),wrap=$("#hanzi");wrap.innerHTML=[...h].map((char,i)=>`<ruby>${char}<rt>${syllables[i]||""}</rt></ruby>`).join("");$("#pinyin").textContent=pinyin||"";$("#meaning").textContent=meaning||"";$("#pinyin").hidden=!$("#pinyinSupport")?.checked;$("#meaning").hidden=!$("#zhSupport")?.checked;ui.card.hidden=false}
function handleVoiceCommand(text){const t=String(text||"").replace(/[，。！？,.!?]/g,"");if(/再说一遍|再讲一遍|重复一下|重复/.test(t)){control("repeat");ui.prompt.textContent="好的，我再说一遍 / I’ll repeat that.";return true}if(/慢一点|慢点|说慢一点|说慢点/.test(t)){control("slower");ui.prompt.textContent="好的，我说慢一点 / I’ll speak more slowly.";return true}if(/提示一下|给个提示|提示|线索/.test(t)){control("hint");ui.prompt.textContent="给你一个提示 / Here’s a hint.";return true}return false}
function stopPlayback(){playbackNextTime=0;for(const node of playbackNodes){try{node.stop()}catch{}}playbackNodes.clear();playbackQueue=Promise.resolve()}
function queuePcm(buffer){playbackQueue=playbackQueue.then(()=>playPcm(buffer)).catch(()=>{});}
function onMessage(event){if(typeof event.data!=="string"){queuePcm(event.data);return}let msg;try{msg=JSON.parse(event.data)}catch{return}if(msg.type==="ready"){sessionId=msg.sessionId;beginAudio().catch(e=>fail(e.message));return}if(msg.type==="speech_started"){stopPlayback();setState("recording","正在听你说");return}if(msg.type==="state")setState(msg.state==="speaking"?"playing":msg.state==="listening"?"recording":"processing",msg.label||"老师正在思考");if(msg.type==="transcript"){addLine(msg.role,msg.text);ui.prompt.textContent=msg.text||ui.prompt.textContent;if(msg.role==="student")handleVoiceCommand(msg.text)}if(msg.type==="word_card")renderWordCard(msg.hanzi,msg.pinyin,msg.meaning);if(msg.type==="error")fail(msg.message||"对话服务暂时不可用");if(msg.type==="ended"){ended=true;cleanup();setState("complete","本次对话已完成");ui.prompt.textContent=msg.summary||"再见！下次我们继续练习。"}}
async function playPcm(buffer){const raw=buffer instanceof Blob?new Uint8Array(await buffer.arrayBuffer()):new Uint8Array(buffer);if(!raw.byteLength||raw.byteLength%2)return;const ac=playbackContext||(playbackContext=new AudioContext());if(ac.state==="suspended")await ac.resume();let audio;if((raw[0]===79&&raw[1]===103&&raw[2]===103)||(raw[0]===82&&raw[1]===73&&raw[2]===70&&raw[3]===70)){audio=await ac.decodeAudioData(raw.buffer.slice(0))}else{const pcm=new Int16Array(raw.buffer,raw.byteOffset,Math.floor(raw.byteLength/2));audio=ac.createBuffer(1,pcm.length,24000);const data=audio.getChannelData(0);for(let i=0;i<pcm.length;i++)data[i]=Math.max(-1,Math.min(1,pcm[i]/32768))}const node=ac.createBufferSource();node.buffer=audio;node.connect(ac.destination);playbackNodes.add(node);node.addEventListener("ended",()=>playbackNodes.delete(node),{once:true});const start=Math.max(ac.currentTime,playbackNextTime);node.start(start);playbackNextTime=start+audio.duration;setState("playing","老师正在说话")}
function control(action){if(!socket)return;send({type:"control",action});if(action==="hint")ui.card.hidden=!ui.card.hidden}
function fail(message){setState("error","连接出现问题");ui.prompt.textContent=message;ui.caption.textContent="请返回学习中心检查登录和网关配置"}
function cleanup(close=true){stopAudio();if(close&&socket?.readyState<2)socket.close();socket=null}
ui.mic.addEventListener("click",()=>{if(!socket)start().catch(e=>fail(e.message));else{send({type:"control",action:"interrupt"});setState("recording","正在听你说")}});document.querySelectorAll("[data-action]").forEach(b=>b.addEventListener("click",()=>control(b.dataset.action)));$("#end").addEventListener("click",()=>{ended=true;send({type:"control",action:"end"});setTimeout(()=>cleanup(),400)});$("#transcriptToggle").addEventListener("click",()=>ui.transcript.hidden=!ui.transcript.hidden);$("#keyboard").addEventListener("click",()=>$("#textDialog").showModal());$("#sendText").addEventListener("click",e=>{e.preventDefault();const text=$("#textInput").value.trim();if(text){send({type:"text",text});addLine("student",text);$("#textInput").value=""}$("#textDialog").close()});window.addEventListener("beforeunload",()=>cleanup());const zhSupport=$("#zhSupport"),pinyinSupport=$("#pinyinSupport");if(zhSupport&&pinyinSupport){zhSupport.checked=localStorage.getItem("diandian-zh-support")==="1";pinyinSupport.checked=localStorage.getItem("diandian-pinyin-support")==="1";zhSupport.addEventListener("change",()=>{localStorage.setItem("diandian-zh-support",zhSupport.checked?"1":"0");$("#meaning").hidden=!zhSupport.checked});pinyinSupport.addEventListener("change",()=>{localStorage.setItem("diandian-pinyin-support",pinyinSupport.checked?"1":"0");$("#pinyin").hidden=!pinyinSupport.checked})}
})();
